# Project information
site_name: 'Material PUEBI'
site_description: 'A short description of my project'
site_author: 'John Doe'
site_url: 'https://mughnimind.github.io/Materi-PUEBI/'

# Repository
repo_name: 'mughnimind/Materi-PUEBI'
repo_url: 'https://github.com/mughnimind/Materi-PUEBI'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 MughniMind'

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/mughnimind'
    - type: 'twitter'
      link: 'https://twitter.com/acemughnie'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde