# Informasi Proyek
site_name: 'Materi PUEBI'
site_description: 'Panduan Umum Ejaan Bahasa Indonesia bernuansa Desain Material'
site_author: 'MughniMind'
site_url: 'https://mughnimind.github.io/materi-puebi/'

# Halaman
pages:
  - 'Beranda': 'index.md'
  - 'Kata Pengantar': 'kata-pengantar/index.md'
  - 'Peraturan KEMDIKBUD': 'peraturan-kemdikbud/index.md'
  - 'Prakata': 'prakata/index.md'
  - 'Pemakaian Huruf':
    - 'Huruf Abjad': 'pemakaian-huruf/huruf-abjad/index.md'
    - 'Huruf Vokal': 'pemakaian-huruf/huruf-vokal/index.md'
    - 'Huruf Konsonan': 'pemakaian-huruf/huruf-konsonan/index.md'
    - 'Huruf Diftong': 'pemakaian-huruf/huruf-diftong/index.md'
    - 'Gabungan Huruf Konsonan': 'pemakaian-huruf/gabungan-huruf-konsonan/index.md'
    - 'Huruf Kapital': 'pemakaian-huruf/huruf-kapital/index.md'
    - 'Huruf Miring': 'pemakaian-huruf/huruf-miring/index.md'
    - 'Huruf Tebal': 'pemakaian-huruf/huruf-tebal/index.md'
  - 'Penulisan Kata':
    - 'Kata Dasar': 'penulisan-kata/kata-dasar/index.md'
    - 'Kata Berimbuhan': 'penulisan-kata/kata-berimbuhan/index.md'
    - 'Bentuk Ulang': 'penulisan-kata/bentuk-ulang/index.md'
    - 'Gabungan Kata': 'penulisan-kata/gabungan-kata/index.md'
    - 'Pemenggalan Kata': 'penulisan-kata/pemenggalan-kata/index.md'
    - 'Kata Depan': 'penulisan-kata/kata-depan/index.md'
    - 'Partikel': 'penulisan-kata/partikel/index.md'
    - 'Singkatan dan Akronim': 'penulisan-kata/singkatan-dan-akronim/index.md'
    - 'Angka dan Bilangan': 'penulisan-kata/angka-dan-bilangan/index.md'
    - 'Kata Ganti': 'penulisan-kata/kata-ganti/index.md'
    - 'Kata Sandang': 'penulisan-kata/kata-sandang/index.md'
  - 'Pemakaian Tanda Baca':
    - 'Tanda Titik': 'pemakaian-tanda-baca/tanda-titik/index.md'
    - 'Tanda Koma': 'pemakaian-tanda-baca/tanda-koma/index.md'
    - 'Tanda Titik Koma': 'pemakaian-tanda-baca/tanda-titik-koma/index.md'
    - 'Tanda Titik Dua': 'pemakaian-tanda-baca/tanda-titik-dua/index.md'
    - 'Tanda Hubung': 'pemakaian-tanda-baca/tanda-hubung/index.md'
    - 'Tanda Pisah': 'pemakaian-tanda-baca/tanda-pisah/index.md'
    - 'Tanda Tanya': 'pemakaian-tanda-baca/tanda-tanya/index.md'
    - 'Tanda Seru': 'pemakaian-tanda-baca/tanda-seru/index.md'
    - 'Tanda Elipsis': 'pemakaian-tanda-baca/tanda-elipsis/index.md'
    - 'Tanda Petik': 'pemakaian-tanda-baca/tanda-petik/index.md'
    - 'Tanda Petik Tunggal': 'pemakaian-tanda-baca/tanda-petik-tunggal/index.md'
    - 'Tanda Kurung': 'pemakaian-tanda-baca/tanda-kurung/index.md'
    - 'Tanda Kurung Siku': 'pemakaian-tanda-baca/tanda-kurung-siku/index.md'
    - 'Tanda Garis Miring': 'pemakaian-tanda-baca/tanda-garis-miring/index.md'
    - 'Tanda Penyingkat atau Apostrof': 'pemakaian-tanda-baca/tanda-penyingkat-atau-apostrof/index.md'
  - 'Penulisan Unsur Serapan': 'penulisan-unsur-serapan/index.md'
  - 'Profil':
    - 'Tentang Materi PUEBI': 'profil/tentang/index.md'

# Hak cipta
copyright: 'Dibuat sepenuh hati oleh &copy; MughniMind'

# Gudang
repo_name: 'mughnimind/materi-puebi'
repo_url: 'https://github.com/mughnimind/materi-puebi'

# Dokumentasi dan Tema
theme: 'material'
theme_dir: 'tema'
site_favicon: 'assets/gambar/favicon.ico'

# Pengaya
extra:
  feature:
    tabs: false
  logo: 'assets/gambar/logo.svg'
  palette:
    primary: 'blue'
    accent: 'red'
## Kolom Komentar
#  disqus: 'acemughnie'
## Aksara
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
## Media Sosial
  social:
    - type: 'github-alt'
      link: 'https://github.com/mughnimind'
    - type: 'instagram'
      link: 'https://www.instagram.com/acemughnie/'
    - type: 'twitter'
      link: 'https://twitter.com/acemughnie'
    - type: 'google-plus'
      link: 'https://plus.google.com/+AceMughnie'
## Css & JavaScript Imbuhan
extra_css:
  - 'assets/ekstra/css-ekstra.css'
  - 'assets/ekstra/tulis.css'
  - 'assets/ekstra/label.css'
extra_javascript:
  - 'assets/ekstra/js-ekstra.js'

# Google Analitik
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Ekstensi
markdown_extensions:
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.details

